import frappe

def add_reqd_custom_fields_in_company():
	if frappe.db.exists("Custom Field", 
		"Company-default_interest_income_account"):
		return
		
	custom_field = frappe.get_doc({
		'allow_on_submit': 0,
		'bold': 0,
		'collapsible': 0,
		'collapsible_depends_on': None,
		'columns': 0,
		'default': None,
		'depends_on': None,
		'description': None,
		'docstatus': 0,
		'doctype': 'Custom Field',
		'dt': 'Company',
		'fieldname': 'default_interest_income_account',
		'fieldtype': 'Link',
		'hidden': 0,
		'ignore_user_permissions': 0,
		'ignore_xss_filter': 0,
		'in_global_search': 0,
		'in_list_view': 0,
		'in_standard_filter': 0,
		'insert_after': 'default_income_account',
		'label': 'Default Interest Income Account',
		'no_copy': 0,
		'options': 'Account',
		'permlevel': 0,
		'precision': '',
		'print_hide': 0,
		'print_hide_if_no_value': 0,
		'print_width': None,
		'read_only': 0,
		'report_hide': 0,
		'reqd': 0,
		'search_index': 0,
		'unique': 0,
		'width': None
	}).save(ignore_permissions=True)

def add_reqd_custom_fields_in_user():
	if frappe.db.exists("Custom Field", "User-dark_theme"): return
		
	custom_field = frappe.get_doc({
		'allow_on_submit': 0,
		'bold': 0,
		'collapsible': 0,
		'collapsible_depends_on': None,
		'columns': 0,
		'default': '1',
		'depends_on': None,
		'description': None,
		'docstatus': 0,
		'doctype': 'Custom Field',
		'dt': 'User',
		'fieldname': 'dark_theme',
		'fieldtype': 'Check',
		'hidden': 0,
		'ignore_user_permissions': 0,
		'ignore_xss_filter': 0,
		'in_global_search': 0,
		'in_list_view': 0,
		'in_standard_filter': 0,
		'insert_after': 'user_image',
		'label': 'Use Dark Theme',
		'no_copy': 0,
		'options': None,
		'permlevel': 0,
		'precision': '',
		'print_hide': 0,
		'print_hide_if_no_value': 0,
		'print_width': None,
		'read_only': 0,
		'report_hide': 0,
		'reqd': 0,
		'search_index': 0,
		'unique': 0,
		'width': None
	}).save(ignore_permissions=True)

def add_reqd_custom_fields_in_customer():
	if not frappe.db.exists("Custom Field", "Customer-tax_id_type"):
		frappe.get_doc({
			'allow_on_submit': 0,
			'collapsible': 0,
			'collapsible_depends_on': None,
			'default': '1',
			'depends_on': None,
			'description': None,
			'docstatus': 0,
			'doctype': 'Custom Field',
			'dt': 'Customer',
			'fieldname': 'tax_id_type',
			'fieldtype': 'Select',
			'hidden': 0,
			'ignore_user_permissions': 0,
			'ignore_xss_filter': 0,
			'in_filter': 0,
			'in_list_view': 0,
			'insert_after': 'territory',
			'label': 'Tax ID Type',
			'no_copy': 0,
			'options': '1\n2\n3',
			'permlevel': 0,
			'precision': '',
			'print_hide': 0,
			'print_hide_if_no_value': 0,
			'print_width': None,
			'read_only': 0,
			'report_hide': 0,
			'reqd': 0,
			'search_index': 0,
			'unique': 0,
			'width': None
		}).save(ignore_permissions=True)

	if not frappe.db.exists("Custom Field", "Customer-customer_jobs_sb"):
		frappe.get_doc({
			'collapsible': 0,
			'print_width': None,
			'no_copy': 0,
			'depends_on': None,
			'doctype': 'Custom Field',
			'reqd': 0,
			'in_list_view': 0,
			'ignore_xss_filter': 0,
			'in_global_search': 0,
			'collapsible_depends_on': None,
			'bold': 0,
			'read_only': 0,
			'print_hide': 0,
			'ignore_user_permissions': 0,
			'label': 'Customer Jobs',
			'print_hide_if_no_value': 0,
			'width': None,
			'docstatus': 0,
			'hidden': 0,
			'permlevel': 0,
			'columns': 0,
			'insert_after': 'language',
			'description': None,
			'search_index': 0,
			'allow_on_submit': 0,
			'precision': '',
			'dt': 'Customer',
			'unique': 0,
			'idx': 20,
			'default': None,
			'in_standard_filter': 0,
			'fieldname': 'customer_jobs_sb',
			'fieldtype': 'Section Break',
			'options': None,
			'report_hide': 0,
		}).save(ignore_permissions=True)

	if not frappe.db.exists("Custom Field", "Customer-customer_job"):
		frappe.get_doc({
			'collapsible': 0,
			'print_width': None,
			'no_copy': 0,
			'depends_on': None,
			'doctype': 'Custom Field',
			'reqd': 0,
			'in_list_view': 0,
			'ignore_xss_filter': 0,
			'in_global_search': 0,
			'collapsible_depends_on': None,
			'bold': 0,
			'read_only': 0,
			'print_hide': 0,
			'ignore_user_permissions': 0,
			'label': '',
			'print_hide_if_no_value': 0,
			'width': None,
			'docstatus': 0,
			'hidden': 0,
			'permlevel': 0,
			'columns': 0,
			'insert_after': 'customer_jobs_sb',
			'description': None,
			'search_index': 0,
			'allow_on_submit': 0,
			'precision': '',
			'dt': 'Customer',
			'unique': 0,
			'idx': 21,
			'default': None,
			'in_standard_filter': 0,
			'fieldname': 'customer_job',
			'fieldtype': 'Table',
			'options': 'Customer Job',
			'report_hide': 0,
		}).save(ignore_permissions=True)

	if not frappe.db.exists("Custom Field", "Customer-customer_references_sb"):
		frappe.get_doc({
			'collapsible': 0,
			'print_width': None,
			'no_copy': 0,
			'depends_on': None,
			'doctype': 'Custom Field',
			'reqd': 0,
			'in_list_view': 0,
			'ignore_xss_filter': 0,
			'in_global_search': 0,
			'collapsible_depends_on': None,
			'bold': 0,
			'read_only': 0,
			'print_hide': 0,
			'ignore_user_permissions': 0,
			'label': 'Customer References',
			'print_hide_if_no_value': 0,
			'width': None,
			'docstatus': 0,
			'hidden': 0,
			'permlevel': 0,
			'columns': 0,
			'insert_after': 'customer_job',
			'description': None,
			'search_index': 0,
			'allow_on_submit': 0,
			'precision': '',
			'dt': 'Customer',
			'unique': 0,
			'idx': 22,
			'default': None,
			'in_standard_filter': 0,
			'fieldname': 'customer_references_sb',
			'fieldtype': 'Section Break',
			'options': None,
			'report_hide': 0,
		}).save(ignore_permissions=True)

	if not frappe.db.exists("Custom Field", "Customer-customer_reference"):
		frappe.get_doc({
			'collapsible': 0,
			'print_width': None,
			'no_copy': 0,
			'depends_on': None,
			'doctype': 'Custom Field',
			'reqd': 0,
			'in_list_view': 0,
			'ignore_xss_filter': 0,
			'in_global_search': 0,
			'collapsible_depends_on': None,
			'bold': 0,
			'read_only': 0,
			'print_hide': 0,
			'ignore_user_permissions': 0,
			'label': '',
			'print_hide_if_no_value': 0,
			'width': None,
			'docstatus': 0,
			'hidden': 0,
			'permlevel': 0,
			'columns': 0,
			'insert_after': 'customer_references_sb',
			'description': None,
			'search_index': 0,
			'allow_on_submit': 0,
			'precision': '',
			'dt': 'Customer',
			'unique': 0,
			'idx': 23,
			'default': None,
			'in_standard_filter': 0,
			'fieldname': 'customer_reference',
			'fieldtype': 'Table',
			'options': 'Customer Reference',
			'report_hide': 0,
		}).save(ignore_permissions=True)
